# Generated by Django 5.0.6 on 2024-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dish_type', models.CharField(choices=[('soup', 'Leves'), ('main_course', 'Főétel'), ('dessert', 'Desszert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leves', models.CharField(default='', max_length=350)),
                ('foetel', models.TextField(default='', max_length=350)),
                ('desszert', models.CharField(default='', max_length=350)),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=350)),
                ('kep_url', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
                ('cim', models.CharField(default='', max_length=350)),
                ('szoveg', models.CharField(default='', max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('desserts', models.ManyToManyField(limit_choices_to={'dish_type': 'dessert'}, related_name='daily_menus_as_dessert', to='marsfaloda_app.dish')),
                ('main_courses', models.ManyToManyField(limit_choices_to={'dish_type': 'main_course'}, related_name='daily_menus_as_main_course', to='marsfaloda_app.dish')),
                ('soups', models.ManyToManyField(limit_choices_to={'dish_type': 'soup'}, related_name='daily_menus_as_soup', to='marsfaloda_app.dish')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_menus', models.ManyToManyField(to='marsfaloda_app.dailymenu')),
            ],
        ),
    ]
