# Generated by Django 5.0.6 on 2024-07-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsfaloda_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
