# Generated by Django 5.0.6 on 2024-07-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsfaloda_app', '0002_delete_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
